@template.layout.page(
header = @`
    <header class="d-flex justify-content-center py-3">
      <ul class="nav nav-pills">
        <li class="nav-item"><a href="/" class="nav-link active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="/users" class="nav-link">Users</a></li>
      </ul>
    </header>
    `,
content = @`
    <div class="px-4 py-5 my-5 text-center">
      <h1 class="display-5 fw-bold">Hello, world!</h1>
    </div>
    `
)
